name: 'Check for merge conflicts'
on:
  push:
    branches:
      - master
jobs:
  triage:
    runs-on: ubuntu-20.04
    steps:
    - name: "Check for ACTION_ENABLER secret and pass true to output if it exists to be checked by later steps"
      id: value_holder
      env:
        ENABLER_SECRET: ${{ secrets.ACTION_ENABLER }}
      run: |
        unset SECRET_EXISTS
        if [ -n "$ENABLER_SECRET" ]; then SECRET_EXISTS=true ; fi
        echo "::set-output name=ACTIONS_ENABLED::$SECRET_EXISTS"
    - name : Label conflicts
      if: steps.value_holder.outputs.ACTIONS_ENABLED
      uses: mschilde/auto-label-merge-conflicts@2e8fcc76c6430272ec8bb64fb74ec1592156aa6a
      with:
        CONFLICT_LABEL_NAME: 'Merge Conflict'
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WAIT_MS: 10000
