name: PR Labeler
on:
  pull_request:
    types: [edited, opened, synchronize, reopened]

jobs:
  apply_labels:
    runs-on: ubuntu-latest
    steps:
    - uses: AnturK/labeler@simple
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
