# This is a separate workflow so that it can access secrets, which are necessary
# because we need to be able to upload the images and post a comment.
# In the event this workflow fails, the screenshot test results are still
# available as an artifact of the screenshot test comparison workflow itself.
# This simply provides necessary quality of life.
name: Show Screenshot Test Results
on:
  workflow_run:
    workflows: [CI Suite]
    types:
      - completed
jobs:
  show_screenshot_test_results:
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    name: Show Screenshot Test Results
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: "Mothblocks/tgstation"
          ref: "screenshot-tests"
      - name: Prepare module
        run: |
          # This is needed because node-fetch needs import and doesn't work with require :/
          echo "{\"type\": \"module\"}" > package.json
          npm install node-fetch
      - name: Show screenshot test results
        uses: actions/github-script@v6
        env:
          # TODO: Don't run if this is not set
          FILE_HOUSE_KEY: ${{ secrets.ARTIFACTS_FILE_HOUSE_KEY }}
        with:
          script: |
            const { showScreenshotTestResults } = await import('${{ github.workspace }}/tools/ci/show_screenshot_test_results.js')
            await showScreenshotTestResults({ github, context, exec })
      # - name: Download artifact
      #   uses: actions/github-script@v3.1.0
      #   id: dl_results
      #   continue-on-error: true
      #   with:
      #     script: |
      #       const artifacts = await github.actions.listWorkflowRunArtifacts({
      #          owner: context.repo.owner,
      #          repo: context.repo.repo,
      #          run_id: ${{github.event.workflow_run.id }},
      #       });

      #       const matchArtifact = artifacts.data.artifacts.filter((artifact) => {
      #         return artifact.name == "bad-screenshots"
      #       })[0];

      #       if (matchArtifact === undefined) {
      #         console.log("No bad-screenshot artifact found")
      #         require("process").exit(1)
      #       }

      #       const download = await github.actions.downloadArtifact({
      #          owner: context.repo.owner,
      #          repo: context.repo.repo,
      #          artifact_id: matchArtifact.id,
      #          archive_format: 'zip',
      #       });

      #       const fs = require('fs');
      #       fs.writeFileSync('${{github.workspace}}/bad-screenshots.zip', Buffer.from(download.data));
      # - name: Extract
      #   if: steps.dl_results.outcome == 'success'
      #   run: unzip bad-screenshots.zip -d bad-screenshots
      # - name: Show screenshot test results
      #   if: steps.dl_results.outcome == 'success'
      #   # MOTHBLOCKS TODO: Move this to a tgstation repository
      #   uses: Mothblocks/show-screenshot-test-results@main
      #   # MOTHBLOCKS TODO: Max file size
      #   with:
      #     file-house-key: ${{ secrets.ARTIFACTS_FILE_HOUSE_KEY }}
      #     repo-token: ${{ secrets.GITHUB_TOKEN }}
      #     screenshots-folder: bad-screenshots
